### ISSUE TITLE
Banned Moves and Abilities

### ISSUE THREAD

**Issue by SoyNegro** [rglezg/Renegade-Emerald#11]
When balancing pokemon we may find some moves and abilities are off-chart thus disturbing the gameplay. Also with the new planned features some moves may not be worthy after having its pp 

- [ ] Delete 1-Hit KO.
- [ ] Delete Pressure Ability.
- [ ] Delete Air Lock Ability. Or Nerf.
- [ ] Standardized Hidden Abilities for Species

**Comment by rglezg** [comment]
I enabled the new `discussions` feature of GitHub. We'll use it for discussing design propossals like this.

**Comment by rglezg** [comment]
1 hit KOs, Pressure and Air Lock has been moved to discussions #13, #15 and #17 respectively. As for standarizing abilities, we will make easy to select the ability you want. De implementation details will be tracked in #18.
